### ISSUE TITLE
Send push events

### ISSUE THREAD

**Issue by elpatron68** [NotSqrt/mattermost-integration-gitlab#10]
I would really like to send push events to a Mattermost channel, this seems not to be possible. Is there a particular reason for this?

Thanks!

**Comment by NotSqrt** [comment]
Push events are not activated by default. You can activate them by using the option `--push` !

**Comment by mohitt** [comment]
Suprisingly, the only events that are showing up is merge request created, merge request accepted and merge request updated. Neither we are getting build related events no push events 

our gitlab settings is enabling all the events
https://mattermost-gitlab-codemerlin.herokuapp.com/new_event
Push Events 
Tag Push Events 
Issues Events 
Note Events 
Merge Requests Events 
Build Events 
Pipeline Events 
Wiki Page Events

The only ones that we are getting are the merge request events. 

Where am I suppose to activate by setting he option --push

**Comment by mohitt** [comment]
How can we log or see whats going on in the heroku deployed app

**Comment by NotSqrt** [comment]
You can add the `--push` option in the command run by Heroku, in the Procfile.

Apart from the standard flask output, there's no particular log.

I've never used Heroku, I don't know where you would be able to see the output of the server.

**Comment by athakral** [comment]
Oh,  I followed the exact instructions given on the readme.md

**Comment by mohitt** [comment]
I followed the exact instructions given on the readme

Regards
Mohit

**Comment by NotSqrt** [comment]
The part that says :
**Heroku-based Install
:exclamation: This was not adapted to the new python package.**
?

If you can provide up-to-date instructions for Heroku, I'll be glad to merge them !

**Comment by qvazzler** [comment]
@NotSqrt This feature really needs to be somewhere on the README, I almost gave up. :-D

**Comment by NotSqrt** [comment]
About to add that mention !
