### ISSUE TITLE
500 Errors when testing a webhook

### ISSUE THREAD

**Issue by kai23** [NotSqrt/mattermost-integration-gitlab#11]
Hello,

I've an already up and running gitlab 8.9.3, and wanted to add a mattermost instance on another server, which I did.

I wanted to add the mattermost-gitlab-integration to mattermost ( https://github.com/NotSqrt/mattermost-integration-gitlab ). The thing is… I get an error 500 everytime I try to contact mattermost via the incomming webhooks (when clicking on "test")

Here is the `production.log` I get : 

```
Started GET "/plus/plus/hooks/32/test" for 185.116.128.22 at 2016-06-30 13:22:51 +0200
Processing by Projects::HooksController#test as HTML
  Parameters: {"namespace_id"=>"plus", "project_id"=>"plus", "id"=>"32"}
Completed 500 Internal Server Error in 745ms (ActiveRecord: 25.0ms)

HTTParty::RedirectionTooDeep (HTTP redirects too deep):
  app/models/hooks/web_hook.rb:24:in `execute'
  app/services/test_hook_service.rb:4:in `execute'
  app/controllers/projects/hooks_controller.rb:28:in `test'
  lib/gitlab/middleware/go.rb:16:in `call'
```

Do you have any idea where I could dig more ?

Thanks

**Comment by NotSqrt** [comment]
Hum, mattermost-gitlab-integration doesn't return any HTTP redirect, so it's probably between mattermost-gitlab-integration and gitlab that something goes wrong..

**Comment by NotSqrt** [comment]
Is there a web server in front of mattermost-gitlab-integration ? nginx ? apache ?

**Comment by kai23** [comment]
Nothing, should I ? I have a nginx which serves the mattermost and that's all

**Comment by NotSqrt** [comment]
No, no particular reason to add a web server, just looking for the responsible of those redirects ..

Are you sure of the url you declared in gitlab ?

**Comment by kai23** [comment]
I've tried a lot different.

I've also tried from postman, further details here : https://github.com/mattermost/platform/issues/2469#issuecomment-229635562

I always get a 404

**Comment by NotSqrt** [comment]
In gitlab, did you declare `http://host:port/new_event` as url, host is probably localhost, port is 5000 by default ?

**Comment by NotSqrt** [comment]
If you do `curl http://host:port/` it should answer `OK`, and you should see a line in the output/logfile of mattermost_gitlab.

**Comment by kai23** [comment]
Yeah I tried it, but the gitlab and the mattermost are not on the same network, It cannot work.
The URL I've tried so far : 
- http://chat.xxxx.xx:5000/hooks/xxxxxx/new_event
- http://chat.xxxx.xx/hooks/xxxxxx/new_event
- http://chat.xxxx.xx/new_event
- http://localhost:5000/new_event
- http://localhost:5000/hooks/xxxxxx/new_event

And it works flawlessly with Rocket.chat :(

**Comment by kai23** [comment]
And I can't curl from the gitlab server to the chat server when I set the port to 5000 like 

```
curl http://chat.xxxxxx.xxx:5000 
curl: (7) Failed to connect to chat.xxxxx.xxxxxx port 5000: Connection refused
```

**Comment by NotSqrt** [comment]
Il faut que tu fasses en sorte que le nom d'hôte indiqué dans l'url de webhook mise dans gitlab soit effectivement accessible depuis le serveur sur lequel est gitlab..

mattermost_gitlab n'est rien de plus qu'un petit serveur web qui sert de relais entre gitlab et mattermost.

**Comment by kai23** [comment]
Ca marche. Je vais voir au niveau du firewall si ça bloque ou pas, ou alors si mon nginx ne fait pas un redirect à un moment donné.
Ou alors, le mieux c'est peut être que je fasse un reverse ?
Dans tous les cas, c'est pas un peu bizarre que je me prenne que des 404 sur les incomming webhooks qui sont créés ? :/

**Comment by kai23** [comment]
Parfait, il semblerait que ce soit mieux. En tout cas, les deux arrivent à parler ensemble, en mettant une ip locale

```
192.168.1.102 - - [01/Jul/2016 08:26:32] "POST /new_event HTTP/1.1" 200 -
```

Ce qui fait que j'ai mis une URL dans le gitlab en 

```
http://192.168.1.71:5000/new_event
```

Par contre, rien n'est affiché dans le gitlab. Si je mets l'adresse du hook plutôt, ça me donne ça : 

```
192.168.1.102 - - [01/Jul/2016 08:28:31] "POST /hooks/b1173ofapiyixprb3uxnpqtffy/new_event HTTP/1.1" 404 -
192.168.1.102 - - [01/Jul/2016 08:32:13] "POST /b1173ofapiyixprb3uxnpqtffy/new_event HTTP/1.1" 404 -
```

Je pense qu'il me manque plus grand chose ! Surtout que de cette manière, ça ne me permet pas d'avoir différents bots par channel

Edit : En fait, j'ai juste un problème au niveau de cette ligne dans la documentation : 

> `mattermost_gitlab $MATTERMOST_WEBHOOK_URL`

Histoire d'être sûr, à quoi correspond `$MATTERMOST_WEBHOOK_URL` ? À quelque chose comme `https://chat.xxxx.xxxx/hooks/su6j84hjaif3tmuubon3icherr` ?

**Comment by NotSqrt** [comment]
> Histoire d'être sûr, à quoi correspond $MATTERMOST_WEBHOOK_URL ? À quelque chose comme https://chat.xxxx.xxxx/hooks/su6j84hjaif3tmuubon3icherr ?

oui !

**Comment by kai23** [comment]
Okay ! Donc il faut que je démarre une instance de `mattermost_gitlab` pour chaque chan / webhook que je souhaite bind au Gitlab ?

Et désolé, je me suis trompé en disant : 

> Par contre, rien n'est affiché dans le gitlab [...]

C'est plutôt 

> Par contre, rien n'est affiché dans le chan mattermost [...]

**Comment by NotSqrt** [comment]
oui, pour le moment il faut une instance de mattermost_gitlab pour chaque channel dans mattermost.
Plusieurs projets gitlab peuvent pointer sur le même mattermost_gitlab, si on veut qu'ils aillent dans le même channel, évidemment.

> rien n'est affiché dans le chan mattermost
> Bizarre, le bouton test de gitlab déclenche l'arrivée d'un message dans mattermost, je viens de tester sur mon install.

**Comment by kai23** [comment]
Ok, je reprends exactement ce que j'ai fait : 

---

Dans Mattermost : 
- Intégration -> webhook entrant -> Ajouter des webhooks entrants

Display Name : "Gitlab"
Description: "Intégration avec le Gitlab"
Channel: "dev"
--> Enregistrer.

Ca me donne un lien : `https://chat.xxx.xxxx/hooks/d6bd3mo77i8g8q3woyc7u3mw6a`

---

Sur le serveur où est hébergé le chat : 

```
mattermost_gitlab https://chat.xxx.xxxx/hooks/d6bd3mo77i8g8q3woyc7u3mw6a
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

---

Dans Gitlab (8.9.3) : 
- Go dans le projet, hooks

URL: http://192.168.1.71:5000/new_event
- [x] push
- [x] comments
- [x] issues
- [x] merge request

décoché "enable ssl verification"
- Click sur "test" : `Hook executed successfully: HTTP 200`

Dans la console de la machine, où est executé `mattermost_gitlab` : 

`192.168.1.102 - - [01/Jul/2016 09:45:25] "POST /new_event HTTP/1.1" 200 -`

Et pourtant… rien dans le chan

**Comment by NotSqrt** [comment]
ça me parait bien.

J'ai juste un doute sur le bon support du https quand mattermost_gitlab essaye de POST le message à mattermost.

et en testant en ajoutant un commentaire sur une issue, ou en créant une issue ?

**Comment by kai23** [comment]
Aaah ! Ca a l'air de marche !

Par contre, j'ai un petit warning : 

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
192.168.1.102 - - [01/Jul/2016 10:00:07] "POST /new_event HTTP/1.1" 200 -
```

Edit: J'ai aussi une petite question: comment tu feras pour différencier sur quel channel envoyer si c'est toujours la même URL qui est mise dans le webhook Gitlab ?
Edit2: Je me réponds à moi même - Ce sera pas le même port

**Comment by NotSqrt** [comment]
:+1: 

Le warning est "normal" avec python < 2.7.9

Yes, avec des ports différents ! (il y a des tentatives de faire ça différents en issues et pull requests, mais je n'ai pas pris le temps de mettre ça au propre)

**Comment by kai23** [comment]
Parfait, ben ça a fini par fonctionner pour moi du coup. Merci de ta présence et de ta réactivité :)

**Comment by natejgardner** [comment]
I'm getting a similar problem.

On Mattermost, I create a new incoming webhook and paste the URL exactly into the Gitlab URL field. I disable SSL verification and click add webhook. I get the message:

```
Hook executed successfully but returned HTTP 500 
{
    "id"=>"web.incoming_webhook.text.app_error",
    "message"=>"No text specified",
    "detailed_error"=>"",
    "request_id"=>"uwpqujub97yiproh5dkipuqmbh",
    "status_code"=>500
}

**Comment by NotSqrt** [comment]
That's not the proper steps !
In mattermost, you create a webhook and use that URL as argument to the mattermost_gitlab command.
In gitlab, you configure a webhook using the url of the python server run by mattermost_gitlab (usually http://your-ip:5000/new_event).
