### ISSUE TITLE
Working with mattermost 3.1 and gitlab 8.9 ?

### ISSUE THREAD

**Issue by webframp** [NotSqrt/mattermost-integration-gitlab#12]
I was testing this with our current gitlab omnibus installed version, gitlab 8.9 and mattermost 3.1, running the flask service on the same server as the both gitlab and mattermost.

After configuring the hook in a gitlab project, when trying to test the hook I saw the following output in the console:

```
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Jul/2016 22:35:10] "POST /new_event HTTP/1.1" 200 -
```

but no message ever arrived in the mattermost channel.

I tried modifying `main()` for debug info with:

``` python
 app.run(host=host, port=port, debug=True)
```

but it didn't provide very useful information.

Does this integration still work with the mentioned versions? If so, where else would I look to debug?

**Comment by NotSqrt** [comment]
I have no problem with up-to-date gitlab and mattermost.

When testing the hook, I think it resends the last message, and if none was ever sent, there's nothing to send to mattermost.

Try actually triggering the hook by creating an issue or submitting a comment !

**Comment by webframp** [comment]
It looks like you're right. The issue seems to be in just testing the hook, triggering the hook with a new issue went further.

Creating a new issue resulted in a Traceback from a urlib3 SSL error, despite having ssl verification disabled. I'm pretty sure this is due to using our internal PKI infrastructure though and I saw another issue that referenced a way to resolve that.

**Comment by NotSqrt** [comment]
Yes, #9 should be helpful.

**Comment by webframp** [comment]
Took just a few extra steps, first https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
then just had to set correct environment

`export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

that resolved it for me
