### ISSUE TITLE
Revising suggestions for systemctl unit creation mentioned in README

### ISSUE THREAD

**Issue by qvazzler** [NotSqrt/mattermost-integration-gitlab#23]
**_Original text_**

> ### Using systemctl
> 
> Another script using `systemctl`:
> 
> - sudo touch `/etc/systemd/system/mattermost_gitlab.service`
> - 'sudo vi /etc/systemd/system/mattermost_gitlab.service`
> - Copy the following lines into /etc/systemd/system/mattermost_gitlab.service
> 
> ```
> [Unit]
> Description=Mattermost gitlab integration
> After=syslog.target network.target
> 
> [Service]
> Type=simple
> User=mattermost
> Group=mattermost
> ExecStart=/usr/local/bin/mattermost_gitlab http://mattermost/hooks/hook-id
> PrivateTmp=yes
> WorkingDirectory=/opt/mattermost
> Restart=always
> RestartSec=30
> LimitNOFILE=49152
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> - `systemctl daemon-reload`
> - `systemctl enable mattermost`
> - `systemctl start mattermost`

**_Suggested text_**

> ### Using systemctl
> 
> Another script using `systemctl`:
> 
> - `sudo chown mattermost:mattermost /usr/local/bin/mattermost_gitlab`
> - `sudo nano /etc/systemd/system/mattermost_gitlab.service`
> - Copy the following lines into `/etc/systemd/system/mattermost_gitlab.service`
> 
> ```
> [Unit]
> Description=Mattermost gitlab integration
> After=syslog.target network.target
> 
> [Service]
> Type=simple
> User=mattermost
> Group=mattermost
> ExecStart=/usr/local/bin/mattermost_gitlab http://mattermost/hooks/hook-id
> PrivateTmp=yes
> WorkingDirectory=/opt/mattermost #for omnibus installations, use /opt/gitlab/embedded/service/mattermost
> Restart=always
> RestartSec=30
> LimitNOFILE=49152
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> - `systemctl daemon-reload`
> - `systemctl enable mattermost_gitlab`
> - `systemctl start mattermost_gitlab`

---

**_Corrections made_**
* Not sure if this is a good idea, but I added instruction to do `chown` command and assign ownership of gitlab_mattermost to user mattermost and group mattermost. Assuming this is the best approach, correct me if chmod is the better option or if this should be skipped entirely.
* systemctl commands at bottom did not reference the correct unit name
* `nano` is better suited for all audiences, hands down.
* working directory needs to be different for omnibus installations, otherwise you'll get a very cryptic error message from /opt/var/syslog. (Reference can be found [here](https://bugs.freedesktop.org/show_bug.cgi?id=89864))

```
Dec 12 10:31:35 gitlab systemd[5406]: mattermost_gitlab.service: Failed at step CHDIR spawning /usr/local/bin/mattermost_gitlab: No such file or directory
```

**Comment by NotSqrt** [comment]
Done !
