### ISSUE TITLE
Event reaches mattermost_gitlab but not mattermost

### ISSUE THREAD

**Issue by Catscrash** [NotSqrt/mattermost-integration-gitlab#27]
Hi,

I would like some help, I have set it up according to the installation and when I press "Test" in the gitlab webhooks page, I see

127.0.0.1 - - [04/Feb/2017 12:16:59] "POST /new_event HTTP/1.1" 200 -

in mattermost_gitlab console, so that looks good, but nothing is being posted in the mattermost channel I chosed. 

I double-checked the webhook-URL and used copy&paste, so a typo there should not be possible.

Is there any way to put the tool into debug / verbose mode to see where / why there is an error?

thanks

**Comment by NotSqrt** [comment]
Gitlab can only resend the last message when clicking the Test button.
When configuring the webhook, no messages have been sent before, so the test message is in fact empty.

You need to trigger a new message : new commit, issue, ...

**Comment by Catscrash** [comment]
I see, it works now, thank you
