### ISSUE TITLE
Error 405

### ISSUE THREAD

**Issue by ghost** [NotSqrt/mattermost-integration-gitlab#31]
Hi guys

I'm having an error in my integration 
When i run the command (mattermost_gitlab -p 10000 --host 10.160.47.84 --no-verify-ssl http://mattermost/hooks/hook_id)
 * Running on http://10.160.47.84:10000/

When i test the hook or make some integration with gitlab i got this response:
10.160.44.226 - - [03/Apr/2017 15:57:01] "POST / HTTP/1.1" 405 -

If someone can help me it will be great!

**Comment by NotSqrt** [comment]
The url you configured in gitlab should be `http://<your-mattermost-integration-URL>/new_event`, not `http://<your-mattermost-integration-URL>/`.

It should be enough !

**Comment by ghost** [comment]
Thanks

Progress :) 
10.160.44.226 - - [03/Apr/2017 16:33:32] "POST /new_event HTTP/1.1" 200 -

I've made a few commits but on mattermost i didnt receive anything... :(
The hook is working because i test with  curl -i -X PT -d 'payload={"text": "Hello, this is some text.\nThis is more text."}' http://mattermost/hooks/hook_id and posts on Mattermost.

**Comment by NotSqrt** [comment]
push messages are not enabled by default.
You can activate them with `--push` in your `mattermost_gitlab` call.

**Comment by ghost** [comment]
It works!! Thanks a lot for the help!!

**Comment by NotSqrt** [comment]
you're welcome !

**Comment by JeremieGuez** [comment]
Hey guys,

I have the same issue event if I type http://<your-mattermost-integration-URL>/new_event 

Need help :)

**Comment by JeremieGuez** [comment]
<img width="1438" alt="Capture d’écran 2020-05-20 à 18 31 59" src="https://user-images.githubusercontent.com/15033641/82472291-403b8280-9ac8-11ea-9909-c99427a31d6e.png">
